server:
  port: 10000
#  port: 10001

spring:
  application:
    name: ex10
  # sql 구문 실행해라
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://maria_container:3306/aaa
    url: jdbc:mariadb://localhost:3307/aaa
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false
    # 스프링부트 시작 한 후에 data.sql 에 있는 insert 구문 실행해라
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0

  jwt:
    secret: abcdefghijklmnopqrstuvwxyz01234567890

my:
  value: "welcome to my value"